sudo: required

services:
  - docker

before_install:
  - docker build -t macpie/tesla_api:travis .

script:
  - docker run macpie/tesla_api:travis /bin/sh -c "rebar3 xref"
  - docker run macpie/tesla_api:travis /bin/sh -c "rebar3 eunit"
  - docker run macpie/tesla_api:travis /bin/sh -c "rebar3 dialyzer"
  - docker run macpie/tesla_api:travis /bin/sh -c "rebar3 ct"
